parameters:
  environment: dev
  environmentDisplayName: DEV
  azureSubscription: 'webinar-arm-sc'
  servicename:
  serviceDisplayName:


jobs:
- deployment: ${{ parameters.serviceDisplayName }}_Deploy
  displayName: Deployment of ${{ parameters.serviceDisplayName }}
  environment: ${{ parameters.environmentDisplayName }}
  strategy:
    runOnce:
      deploy:
        steps:
        - download: current
          artifact: ${{ parameters.servicename }}
        - task: AzureFunctionApp@1
          displayName: 'Azure Function Deploy: ${{ parameters.environmentDisplayName }} in ${{ parameters.environmentDisplayName }}'
          inputs:
            azureSubscription: ${{ parameters.azureSubscription }}
            appType: functionAppLinux
            appName: '${{ parameters.servicename }}'
            package: '$(Pipeline.Workspace)/${{ parameters.servicename }}/$(buildConfiguration)/function.zip'
            startUpCommand: 'func azure functionapp publish ${{ parameters.servicename }} --no-bundler'
            appSettings: 
              '-ServiceBus_connection_string $(ServiceBus-connection-string-${{ parameters.environment }})
              -public_IP $(public_IP)
              -function_hostname $(function_hostname)
              -QueueName $(QueueName)'   